{% set pypi_name = "marshmallow_dataclass" %}
{% set conda_name = "marshmallow-dataclass" %}
{% set version = "8.5.9" %}

package:
  name: {{ conda_name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: 68493f6f8bac0a87043a15d1d702927a61736926043766a92c5da51f19dd8fee

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dataclasses
    - marshmallow >=3.0.0,<4.0
    - marshmallow-enum
    - python >=3.6
    - typeguard
    - typing_inspect

test:
  imports:
    - marshmallow_dataclass

about:
  home: https://github.com/lovasoa/marshmallow_dataclass
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python library to convert dataclasses into marshmallow schemas.
  doc_url: https://lovasoa.github.io/marshmallow_dataclass/html/index.html
  dev_url: https://github.com/lovasoa/marshmallow_dataclass

extra:
  recipe-maintainers:
    - lovasoa
    - ElenaBossolini
